version: "3.9"

services:

  postgres:
    image: postgres:latest
    container_name: avira-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5455:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:latest
    container_name: avira-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # management UI
      - "5552:5552"      # stream protocol
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    command: >
      bash -c "
      rabbitmq-plugins enable --offline rabbitmq_management rabbitmq_stream rabbitmq_stream_management &&
      rabbitmq-server
      "

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: avira-keycloak
    restart: unless-stopped
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
  rabbitmq_data: