apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: avira/iam-service
    newTag: local
  - name: avira/platform-service
    newTag: local
  - name: avira/application-service
    newTag: local


