apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-initialization-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-initialization-service
  template:
    metadata:
      labels:
        app: application-initialization-service
    spec:
      containers:
        - name: application-initialization-service
          image: avira/application-initialization-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10000
          envFrom:
            - configMapRef:
                name: avira-app-env
            - secretRef:
                name: avira-app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: application-initialization-service
spec:
  selector:
    app: application-initialization-service
  ports:
    - port: 10000
      targetPort: 10000

