apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-service
  template:
    metadata:
      labels:
        app: business-service
    spec:
      containers:
        - name: business-service
          image: avira/business-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10006
          envFrom:
            - configMapRef:
                name: avira-app-env
            - secretRef:
                name: avira-app-secret
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: avira-app-env
                  key: DB_URL_BUSINESS
---
apiVersion: v1
kind: Service
metadata:
  name: business-service
spec:
  selector:
    app: business-service
  ports:
    - port: 10006
      targetPort: 10006

