apiVersion: v1
kind: Secret
metadata:
  name: iam-service-secret
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  KEYCLOAK_BACKEND_CLIENT_SECRET: change-me-backend-secret
