apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam-service
  template:
    metadata:
      labels:
        app: iam-service
    spec:
      containers:
        - name: iam-service
          image: avira/iam-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10003
          envFrom:
            - configMapRef:
                name: avira-app-env
            - secretRef:
                name: avira-app-secret
          env:
            - name: IAM_SERVER_PORT
              value: "10003"
            - name: IAM_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: avira-app-env
                  key: DB_URL_IAM
            - name: IAM_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: avira-app-env
                  key: DB_USERNAME
            - name: IAM_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: avira-app-secret
                  key: DB_PASSWORD
            - name: KEYCLOAK_TOKEN_URL
              value: http://host.docker.internal:8080/realms/avira-platform/protocol/openid-connect/token
            - name: KEYCLOAK_LOGOUT_URL
              value: http://host.docker.internal:8080/realms/avira-platform/protocol/openid-connect/logout
---
apiVersion: v1
kind: Service
metadata:
  name: iam-service
spec:
  selector:
    app: iam-service
  ports:
    - port: 10003
      targetPort: 10003

