apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true

    services:
      - name: iam-service
        url: http://iam-service:8080
        routes:
          - name: iam-service-routes
            paths:
              - /api/iam/users
              - /api/iam/client
              - /api/iam/internal
              - /api/iam/auth
            strip_path: false
      - name: platform-service
        url: http://platform-service:8080
        routes:
          - name: platform-service-routes
            paths:
              - /api/platform
            strip_path: false
      - name: application-service
        url: http://application-service:8080
        routes:
          - name: application-service-routes
            paths:
              - /api/apps
            strip_path: false
