apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: avira

resources:
  - namespace.yaml
  - configmap-app-env.yaml
  - secret-app-env.yaml
  - iam-service.yaml
  - kong.yaml

