apiVersion: v1
kind: Secret
metadata:
  name: avira-app-secret
type: Opaque
stringData:
  DB_PASSWORD: postgres
  KEYCLOAK_ADMIN_USERNAME: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  AVIRA_MESSAGING_RABBIT_STREAM_PASSWORD: admin
  AVIRA_RABBIT_STREAM_PASSWORD: admin

