apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: avira/user-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10000
          envFrom:
            - configMapRef:
                name: avira-app-env
            - secretRef:
                name: avira-app-secret
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: avira-app-env
                  key: DB_URL_USER
            - name: SPRING_PROFILES_ACTIVE
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 10000
      targetPort: 10000

