iam:
  init:
    keycloak:
      enabled: true
      base-url: http://localhost:8080
      admin-realm: master
      admin-client-id: admin-cli
      admin-username: ${KEYCLOAK_ADMIN:admin}
      admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
      default-tenant-id: default-saas
      shared-realm: avira-platform
      dedicated-prefix: tenant_
      frontend-client-id: saas-frontend
      backend-client-id: saas-backend
      backend-client-secret: ${KEYCLOAK_BACKEND_CLIENT_SECRET:change-me-backend-secret}
  auth:
    provider: keycloak
    keycloak:
      base-url: http://localhost:8080
      frontend-client-id: saas-frontend
      backend-client-id: saas-backend
      backend-client-secret: ${KEYCLOAK_BACKEND_CLIENT_SECRET:change-me-backend-secret}
