spring.application.name=iam-service
spring.config.import=optional:classpath:application-init.yml

iam.realm.shared-name=avira-platform
iam.realm.dedicated-prefix=tenant_
iam.realm.saas-realm-name=saas
iam.realm.admin-realm=master
iam.realm.saas-client-id=saas-backend
iam.realm.tenant-backend-client-pattern=tenant-%s-backend
